architecture-beta
    group api(logos:aws-lambda)[API]

    service db(logos:aws-aurora)[d] in api
    service disk1(logos:aws-glacier)[s] in api
    service disk2(logos:aws-s3)[s2] in api
    service server(logos:aws-ec2)[sv] in api
    service alert(mdi:alert-octagram)[alert] in api
    
    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
